name: mealsplit

description: MealSplit es una aplicación diseñada para facilitar la división y gestión de los gastos en comidas grupales. Ya sea en cenas con amigos, almuerzos de negocios o eventos familiares, MealSplit permite a los usuarios registrar los costos de manera eficiente y precisa, asegurando que cada persona pague su parte justa. La app puede integrar funciones como la captura de recibos, la división de costos por ítems específicos, y opciones de pago directo entre usuarios. Además, ofrece una interfaz intuitiva y amigable, con opciones para ajustar las divisiones según las preferencias de cada grupo y monitorear el historial de gastos compartidos.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
